### ISSUE TITLE
New input raster for UCB model

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#1]
Hi Chris, just a note to enable new rasters for input for the parameters of UCB urban fire model. Thanks.

**Comment by lautenberger** [comment]
Hi Dwi- I'll need more specifics, please provide a description of each raster so that I can use appropriate variable names and input keywords. Thank you!

**Comment by dwimjpurnomo** [comment]
Hi Chris,

It would be
REAL: Peak HRR (HRR_PEAK), FTP per area (FTP_PA), DFC coefficient
(DFC_COEFF), radiation coefficient (RAD_COEFF)
INTEGER: 3 time constants = early stage (EARLY_TIME), fully developed
(DEVELOPED_TIME), decay (DECAY_TIME).

Please let me know if this information is not enough.


Regards
Dwi Marhaendro J Purnomo

**Comment by lautenberger** [comment]
@dwimjpurnomo In addition to the above, don't we also need building area and separation distance?

@yqin123 I believe we would also need a raster for BLDG_FOOTPRINT_FRAC?

**Comment by dwimjpurnomo** [comment]
Hi Chris,

We already have them, no?

Best,

Dwi

**Comment by yqin123** [comment]
@lautenberger Hi Chris, Yes, it would be great if you could add a raster for BLDG_FOOTPRINT_FRAC.

> @dwimjpurnomo In addition to the above, don't we also need building area and separation distance?
> 
> @yqin123 I believe we would also need a raster for BLDG_FOOTPRINT_FRAC?

**Comment by lautenberger** [comment]
@dwimjpurnomo regarding input rasters for urban/WUI spread, ELMFIRE currently has rasters for Hamada model inputs - `HAMADA_A`, `HAMADA_D`, and `HAMADA_FB` for area, separation distance, and burnable fraction respectively. 

However, I would like to make this more general and rename them `BLDG_AREA`, `BLDG_SEPARATION_DIST`, `BLDG_NONBURNABLE_FRAC` or similar and also create a new namelist group - probably named `&URBAN` or `&WUI` - for all of the urban/WUI inputs. So I think that means our updated list of WUI/urban spread rasters is:

* `BLDG_AREA`:  Input. Average area of building in a pixel (sq m)
* `BLDG_SEPARATION_DIST`:  Input. Separation distance between buildings (m). This is a function of wind direction so it will be a 3D array where the "z" index corresponds to wind direction bin
* `BLDG_NONBURNABLE_FRAC`: Input. Fraction of buildings that are nonburnable, this is a holdover from the Hamada model

@dwimjpurnomo I wasn't sure if the above rasters `HRR_PEAK`, `FTP_PA`, `DFC_COEFF`, `RAD_COEFF`, `EARLY_TIME`, `DEVELOPED_TIME`, and `DECAY_TIME`  are INPUTS or rather intermediate quantities that are calculated at run time? They look to me like they're not inputs but I thought I'd check.

**Comment by dwimjpurnomo** [comment]
Hi Chris,

At the moment, the model still need input of HRR etc as inputs, such as
from FDS simulation. So they are not calculated when we run elmfire.

Best,

Dwi

**Comment by lautenberger** [comment]
@dwimjpurnomo I don't think it makes sense to specify HRR directly as a raster input as that would require a 30 m resolution multiband raster to account for the temporal nature of HRR - too much memory and i/o overhead. 

I'd prefer an approach similar to how surface fuel models are used to look up parameters for the Rothermel model. You could define different building HRR archetypes - analogous to fuel models - and then hit a lookup table to get HRR(t) for that particular building archetype. The HRR curve could be specified by a `&RAMP` function similar to FDS or as a csv file, for example. With this approach, the necessary raster input becomes an integer HRR archetype code, analogous to a fuel model, plus a specification of HRR(t) (and possibly other parameters) for each archetype. Let's discuss this in our meeting later today.

**Comment by lautenberger** [comment]
Merged into main.
