### ISSUE TITLE
New version doesn't give tif outputs

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#13]
I tried without using any urban model first, but it didn't give me any .tif outputs. It run, but the only output are spotting outputs in csv files. The error message is that no .bin, .bil, .hdr files are found, which means that those files are not created during the simulation unlike the older version.

**Comment by lautenberger** [comment]
Thank you Dwi - please attach the complete input deck and I'll take a look

**Comment by dwimjpurnomo** [comment]
This is the link for the input decks.
https://drive.google.com/file/d/13ao5LS3dPjZM06qBn6YivJP7AVO4xN0n/view?usp=drive_link

**Comment by dwimjpurnomo** [comment]
This is the link for the input deck.
https://drive.google.com/file/d/13ao5LS3dPjZM06qBn6YivJP7AVO4xN0n/view?usp=sharing

**Comment by lautenberger** [comment]
Got it, thanks. Will have a look at it now

**Comment by lautenberger** [comment]
OK, here's what I did after un-compressing the `debug.rar` file to a local folder:
```
clauten@celsius:~/dwi-debug$ mkdir scratch
clauten@celsius:~/dwi-debug$ mkdir misc
clauten@celsius:~/dwi-debug$ cp $ELMFIRE_BASE_DIR/build/source/fuel_models.csv ./misc
clauten@celsius:~/dwi-debug$ $ELMFIRE_INSTALL_DIR/elmfire_debug elmfire.data
```
ELMFIRE runs and terminates with this error:

```
At line 662 of file ../../source/elmfire_level_set.f90
Fortran runtime error: Index '1' of dimension 3 of array 'bldg_footprint_frac%r4' above upper bound of 0
```
Basically, ELMFIRE throws an error when it tires to access the building footprint fraction raster which hasn't been allocated yet.

Line 662 of `elmfire_level_set.f90` is a call to the enhanced spotting routines being developed by @yqin123 which expects a building footprint fraction raster. To use the "old" spotting algorithm (which doesn't need the building footprint fraction raster) you can set `USE_SUPERSEDED_SPOTTING = .TRUE.` (the default setting) in the `&SPOTTING` namelist group.

Alternatively, in the `&WUI` namelist group you could set `USE_BLDG_SPREAD_MODEL = .TRUE.` and then specify filenames for input rasters, or use constant parameters - see [this comment in Issue #1](https://github.com/lautenberger/elmfire/issues/1#issuecomment-1561351648) for details.

**Comment by lautenberger** [comment]
I've trapped this by adding some checking on the inputs side:

https://github.com/lautenberger/elmfire/commit/fe087a18ecad5db183a613b77c3e25c2455b2d5e
