### ISSUE TITLE
Issue Loading Fuel Types and Running with Pre-defined Tifs

### ISSUE THREAD

**Issue by masonlee277** [lautenberger/elmfire#14]
I am attempting to run ELMFIRE from tifs already created therefor not using the wx.csv nor the CLOUDFIRE api to gather and create weather data.

When I run this script I am not able to load the fuel_models.csv. I attempted to change the relative path to an absolute path in elmfire_init.f90 but it still failed and was not registering any changes that I had made. I also changed the paths in elmfire.data.in but this didn't affect the error either.

There is either an error in my script that I created for this or a bug in the source. When I run the other tutorials they work fine. I 

Code
https://drive.google.com/drive/folders/1sP0oEhmt_IDsRz8xt73A1xs3i_u0fgv-?usp=sharing
In some runs I get the error:
./01-run.sh: line 98: elmfire_2023.06: command not found

mostly I get.
OUTPUT OF RUNNING CODE:
[mnlee2@gs611-hammer elmfire_creek_2.5]$ ./01-run.sh
Starting the script.
Simulation stop time set to: 347400.0 seconds
ELMFIRE_SCRATCH_BASE=/home/mnlee2/scratch
ELMFIRE_BASE_DIR=/home/mnlee2/elmfire/
ELMFIRE_INSTALL_DIR=/home/mnlee2/elmfire/build/linux/bin
CLOUDFIRE_SERVER=172.92.17.198
PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/mpich-3.2/bin:/usr/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/mnlee2/.local/bin:/home/mnlee2/bin:/home/mnlee2/elmfire/build/linux/bin:/home/mnlee2/elmfire/cloudfire
Deleted existing output directory (if any).
Copied fuel load csv to misc
***************************
The contents of the Misc directory are:
fuel_models.csv
1,FBFM01,.FALSE.,0.034,0,0,0,0,3500,9999,9999,1,12,8000
2,FBFM02,.FALSE.,0.092,0.046,0.023,0.023,0,3000,1500,9999,1,15,8000
3,FBFM03,.FALSE.,0.138,0,0,0,0,1500,9999,9999,2.5,25,8000
4,FBFM04,.FALSE.,0.23,0.184,0.092,0,0.23,2000,9999,1500,6,20,8000
5,FBFM05,.FALSE.,0.046,0.023,0,0,0.092,2000,9999,1500,2,20,8000
6,FBFM06,.FALSE.,0.069,0.115,0.092,0,0,1750,9999,9999,2.5,25,8000
7,FBFM07,.FALSE.,0.052,0.086,0.069,0,0.017,1750,9999,1550,2.5,40,8000
8,FBFM08,.FALSE.,0.069,0.046,0.115,0,0,2000,9999,9999,0.2,30,8000
9,FBFM09,.FALSE.,0.134,0.019,0.007,0,0,2500,9999,9999,0.2,25,8000
10,FBFM10,.FALSE.,0.138,0.092,0.23,0,0.092,2000,9999,1500,1,25,8000
11,FBFM11,.FALSE.,0.069,0.207,0.253,0,0,1500,9999,9999,1,15,8000
12,FBFM12,.FALSE.,0.184,0.644,0.759,0,0,1500,9999,9999,2.3,20,8000
13,FBFM13,.FALSE.,0.322,1.058,1.288,0,0,1500,9999,9999,3,25,8000
14,FBFM14,.FALSE.,0.045913682,0.022956841,0,0,0,2000,2000,2000,0.2,25,8000
15,FBFM15,.FALSE.,0.027548209,0.009182736,0,0,0.059687787,2000,2000,1500,1.2,25,8000
101,GR1,.TRUE.,0.00459,0,0,0.01377,0,2200,2000,9999,0.4,15,8000
102,GR2,.TRUE.,0.00459,0,0,0.04591,0,2000,1800,9999,1,15,8000
103,GR3,.TRUE.,0.00459,0.01837,0,0.06887,0,1500,1300,9999,2,30,8000
104,GR4,.TRUE.,0.01148,0,0,0.08724,0,2000,1800,9999,2,15,8000
105,GR5,.TRUE.,0.01837,0,0,0.11478,0,1800,1600,9999,1.5,40,8000
106,GR6,.TRUE.,0.00459,0,0,0.15611,0,2200,2000,9999,1.5,40,9000
107,GR7,.TRUE.,0.04591,0,0,0.24793,0,2000,1800,9999,3,15,8000
108,GR8,.TRUE.,0.02296,0.04591,0,0.33517,0,1500,1300,9999,4,30,8000
109,GR9,.TRUE.,0.04591,0.04591,0,0.41322,0,1800,1600,9999,5,40,8000
121,GS1,.TRUE.,0.00918,0,0,0.02296,0.02984,2000,1800,1800,0.9,15,8000
122,GS2,.TRUE.,0.02296,0.02296,0,0.02755,0.04591,2000,1800,1800,1.5,15,8000
123,GS3,.TRUE.,0.01377,0.01148,0,0.06657,0.05739,1800,1600,1600,1.8,40,8000
124,GS4,.TRUE.,0.08724,0.01377,0.00459,0.15611,0.32599,1800,1600,1600,2.1,40,8000
141,SH1,.TRUE.,0.01148,0.01148,0,0.00689,0.05969,2000,1800,1600,1,15,8000
142,SH2,.FALSE.,0.06198,0.11019,0.03444,0,0.17677,2000,9999,1600,1,15,8000
143,SH3,.FALSE.,0.02066,0.13774,0,0,0.28466,1600,9999,1400,2.4,40,8000
144,SH4,.FALSE.,0.03903,0.0528,0.00918,0,0.11708,2000,1800,1600,3,30,8000
145,SH5,.FALSE.,0.16529,0.09642,0,0,0.13315,750,9999,1600,6,15,8000
146,SH6,.FALSE.,0.13315,0.06657,0,0,0.06428,750,9999,1600,2,30,8000
147,SH7,.FALSE.,0.1607,0.24334,0.10101,0,0.15611,750,9999,1600,6,15,8000
148,SH8,.FALSE.,0.09412,0.15611,0.03903,0,0.19972,750,9999,1600,3,40,8000
149,SH9,.TRUE.,0.20661,0.11249,0,0.07117,0.3214,750,1800,1500,4.4,40,8000
161,TU1,.TRUE.,0.00918,0.04132,0.06887,0.00918,0.04132,2000,1800,1600,0.6,20,8000
162,TU2,.FALSE.,0.04362,0.08264,0.05739,0,0.00918,2000,9999,1600,1,30,8000
163,TU3,.TRUE.,0.05051,0.00689,0.01148,0.02984,0.05051,1800,1600,1400,1.3,30,8000
164,TU4,.FALSE.,0.20661,0,0,0,0.09183,2300,9999,2000,0.5,12,8000
165,TU5,.FALSE.,0.18365,0.18365,0.13774,0,0.13774,1500,9999,750,1,25,8000
181,TL1,.FALSE.,0.04591,0.10101,0.16529,0,0,2000,9999,9999,0.2,30,8000
182,TL2,.FALSE.,0.06428,0.1056,0.10101,0,0,2000,9999,9999,0.2,25,8000
183,TL3,.FALSE.,0.02296,0.10101,0.12856,0,0,2000,9999,9999,0.3,20,8000
184,TL4,.FALSE.,0.02296,0.06887,0.19284,0,0,2000,9999,9999,0.4,25,8000
185,TL5,.FALSE.,0.0528,0.11478,0.20202,0,0,2000,9999,1600,0.6,25,8000
186,TL6,.FALSE.,0.11019,0.0551,0.0551,0,0,2000,9999,9999,0.3,25,8000
187,TL7,.FALSE.,0.01377,0.06428,0.3719,0,0,2000,9999,9999,0.4,25,8000
188,TL8,.FALSE.,0.2663,0.06428,0.05051,0,0,1800,9999,9999,0.3,35,8000
189,TL9,.FALSE.,0.30533,0.15152,0.19054,0,0,1800,9999,1600,0.6,35,8000
201,SB1,.FALSE.,0.06887,0.13774,0.50505,0,0,2000,9999,9999,1,25,8000
202,SB2,.FALSE.,0.20661,0.19513,0.18365,0,0,2000,9999,9999,1,25,8000
203,SB3,.FALSE.,0.25253,0.12626,0.13774,0,0,2000,9999,9999,1.2,25,8000
204,SB4,.FALSE.,0.24105,0.1607,0.24105,0,0,2000,9999,9999,2.7,25,8000
256,NB,.FALSE.,0.0001,0,0,0,0,9999,9999,9999,0.01,5,1
***************************
The contents of the Input directory are:
adj.tif                       cbh.tif  elmfire.data       m100.tif  phi.tif.aux.xml
asp.tif                       cc.tif   fbfm40.tif         m10.tif   slp.tif
ca-creek_20200905_013000.ctl  ch.tif   fuel_models.csv    m1.tif    wd.tif
cbd.tif                       dem.tif  ignition_mask.tif  phi.tif   ws.tif
***************************
The contents of the Output directory are:
***************************
Copied elmfire.data.in to elmfire.data in the inputs directory.
xmin: 268365.396
xmax: 328365.396
ymin: 4089588.178
ymax: 4149588.178
Extracted geospatial metadata from the fbfm40.tif file.
Calculated the center of the domain as X: 298365.396 and Y: 4119588.178.
Extracted spatial reference system as: +proj=utm +zone=11 +datum=WGS84 +units=m +no_defs  and cell size as: 30.000000000000000.
Creating output file that is 200P x 200L.
Processing input file ./inputs/adj.tif.
Using internal nodata values (e.g. -9999) for image ./inputs/adj.tif.
0...10...20...30...40...50...60...70...80...90...100 - done.
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
Set parameters in the elmfire.data file.
 ELMFIRE 2023.06
 Reading &MISCELLANEOUS namelist group
 Reading &INPUTS namelist group
 Reading &OUTPUTS namelist group
 Reading &COMPUTATIONAL_DOMAIN namelist group
 Reading &TIME_CONTROL namelist group
 Reading &SIMULATOR namelist group
 Reading &WUI namelist group
 Reading &CALIBRATION namelist group
 Reading &SUPPRESSION namelist group
 Reading &SPOTTING namelist group
 Reading &SMOKE namelist group
 Reading &MONTE_CARLO namelist group
 Problem opening fuel model table file /fuel_models.csv
Finished running the ELMFIRE simulation.
The contents of the Output directory are:
ERROR 4: `./outputs/*.bil' does not exist in the file system,
and is not recognised as a supported dataset name.

GDALOpen failed - 4
`./outputs/*.bil' does not exist in the file system,
and is not recognised as a supported dataset name.

Converted ./outputs/*.bil to GeoTIFF.
ls: cannot access ./outputs/time_of_arrival*.tif: No such file or directory
Usage: gdal_contour [-b <band>] [-a <attribute_name>] [-3d] [-inodata]
                    [-snodata n] [-f <formatname>] [-i <interval>]
                    [-f <formatname>] [[-dsco NAME=VALUE] ...] [[-lco NAME=VALUE] ...]
                    [-off <offset>] [-fl <level> <level>...]
                    [-nln <outlayername>] [-q]
                    <src_filename> <dst_filename>

FAILURE: Missing destination filename.

**Comment by lautenberger** [comment]
Thanks, will take a look. Can you give chris.lautenberger@gmail.com access to the Google Drive?

**Comment by masonlee277** [comment]
> Thanks, will take a look. Can you give [chris.lautenberger@gmail.com](mailto:chris.lautenberger@gmail.com) access to the Google Drive?

Done

**Comment by lautenberger** [comment]
@masonlee277 - I pulled the input deck from the google drive link above, simplified it, and updated it for the current code. This [input deck ](https://www.dropbox.com/s/6d6ky9dxyzplvsw/2023-06-28_sample_input_deck.tgz?dl=1) is running correctly on my end, let me know if you encounter any problems running it on your end.

**Comment by lautenberger** [comment]
Closing this issue, please submit a new one if you encounter any additional challenges!
