### ISSUE TITLE
Non uniform fireline intensity when activating spotting model

### ISSUE THREAD

**Issue by yqin123** [lautenberger/elmfire#19]
Hi Chris,

Sorry for the late post. As discussed before, when I apply uniform fuel type (102) and constant wind speed (north to south, 15 mph), the fireline intensity is not uniform when I activate the spotting model. When I deactivate the spotting model, this issue of non-uniform occurs at the boundaries of the simulation region. 
I suspect that it could be a problem due to my enforcing the value of the level-set variable at spotting ignited pixels to be -1 at every time step. Because it happens at the boundary in the no-spotting cases where the level-set variable is also enforced to be -1. But I am not sure how exactly it could impact the fireline intensity calculation.
I attached the input files I used to run the cases with/without spotting. I pulled the newest version of ELMFIRE and used it to test the cases.[test_cases.zip](https://github.com/lautenberger/elmfire/files/11938024/test_cases.zip)

Thanks,
Yiren

**Comment by lautenberger** [comment]
Thank you Yiren, I will take a look after the 4th of July holiday! 

Your initial thinking is that this is caused by forcing the level set function to -1 in cells that are ignited by spotting?

**Comment by lautenberger** [comment]
@yqin123 I tried running the input decks in `test_cases.zip` but it seems that there is not a complete set of inputs? Could you either 1) create and post a link to an updated zip file with all necessary inputs, or 2) Update the scripts to generate the inputs on the fly and test it in an empty directory? I'll look into this after that. Thanks!

**Comment by yqin123** [comment]
Hi Chris, 

Sorry for the late feedback. I got some trouble downloading results from the server at UMD recently. I re-implemented ELMFIRE locally these days and here are the input files. (raster inputs and elmfire.data inputs are all given in the directory 'inputs'). [test_cases.zip](https://github.com/lautenberger/elmfire/files/12026843/test_cases.zip)

Thanks,
Yiren

**Comment by yqin123** [comment]
Hi Chris,

The problem is solved. The fireline intensity is calculated from the spreading velocity of the fire. The velocity is not the maximum velocity predicted by the Rothermel model but the projected velocity normal to the fire perimeter. Therefore, the fireline intensity is different in all directions when affected by wind. 

When firebrand showering is activated in ELMFIRE, independent spot fires will create non-uniform fireline intensity around them, and for the linear fire spreading without embers, fire spreading towards the edges also has a different fireline intensity due to the same issue.

Thanks,
Yiren
