### ISSUE TITLE
Adapting Elmfire_2023.0715 for Kincade Fire Adjustments

### ISSUE THREAD

**Issue by MaryamZamanialaei** [lautenberger/elmfire#27]
Hi Chris,

I've utilized the most recent edition of elmfire for Kincade and have [enclosed](https://drive.google.com/drive/u/0/folders/12sQ1GghHTrhRNWE7ikYwrgPWfVt_rvap) the results for your evaluation. I attempted to incorporate the suppression algorithm into the `elmfire.data` and also experimented with the adjusted fuel. However, I'm uncertain about the steps to modify the `01-run.sh` for a re-run. Your assistance with this matter would be greatly appreciated. Thanks!

Best,
Maryam

**Comment by lautenberger** [comment]
Hi Maryam- thanks for submitting this issue, I will take a look ASAP!

**Comment by lautenberger** [comment]
Hi Maryam- These runs assume a specific directory structure so some modifications are necessary to. To that end, try putting these two files in the same directory as the `ca-kincade_20191024_090000_51h` folder, do a `chmod +x *.sh`, then `cd` to that directory and execute the "newrun" script as `./00-newrun.sh`. 

If all goes well, that script will copy the inputs from the  `ca-kincade_20191024_090000_51h` folder to a new folder, make some edits to the input files, and then launch the run. When it's complete you should be left with 100 time of arrival files. I've tested this and it works on my end, it takes about 2 minutes including pre and post processing on one of my local machines.

**Comment by MaryamZamanialaei** [comment]
Hi Chris- Thank you for the clarifications. I'll work on it and share the results.

**Comment by MaryamZamanialaei** [comment]
Hi Chris- I've implemented the changes you recommended, and it shows the 100 time of arrival files on my end. Thank you for the modifications.

**Comment by lautenberger** [comment]
Excellent, glad to hear it worked!  Closing this issue.
