### ISSUE TITLE
Feature request: size-censored ignitions

### ISSUE THREAD

**Issue by vvvvalvalval** [lautenberger/elmfire#29]
**Problem statement:** in some calibration use cases, the users need not know how a simulated fire spreads after having exceeded a certain size threshold. It makes sense to configure this on a per-fire basis.

**Proposed solution:** in the `IGNITIONS_CSV_FILENAME` file, allow an optional new column `stop_above_atotal`, providing a threshold in acres. For example, the following ignitions CSV

```
icase, iwx_band, x, y, stop_above_atotal
...
19, 342, 572416.24, 1067098.27, 100.0
20, 351, 572424.16, 1067027.98, 10.0
...
```

means that:
- the simulated fire identified by `icase=19` should stop being simulated if it exceeds 100 acres, while
- the simulated fire identified by `icase=20` should stop being simulated if it exceeds 10 acres.

Outputs should still be emitted even if these thresholds are reached.

**Comment by lautenberger** [comment]
Thanks Val- it's on the list!

**Comment by lautenberger** [comment]
OK, this one was fairly straightforward. It's been implemented by commit https://github.com/lautenberger/elmfire/commit/f3ebb70d48bb2ef47830e20f146cf3718fb497f4.
