### ISSUE TITLE
Tubbs fire input decks

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#35]
https://drive.google.com/file/d/1QZNJwqDyKahPp-am9lqUfx1LAvFSs_Qr/view?usp=sharing

**Comment by lautenberger** [comment]
Is this the input deck for issue #36 or something else?

**Comment by dwimjpurnomo** [comment]
This is for speeding up. Issue #36 has an error even with the tutorial input deck.

**Comment by lautenberger** [comment]
OK, I'm going to post the Tubbs Fire input deck at Issue #16 and close this issue out.
