### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#36]
I tried the new version in the main branch but it doesn't work. It is fine using the one I modified last.
<img width="486" alt="image" src="https://github.com/lautenberger/elmfire/assets/38124875/f00e9039-d4f4-419b-9c34-5528acd0cfbe">

**Comment by lautenberger** [comment]
Dwi, I can't diagnose this without an input deck but if you can post the complete input deck and I'll take a look.

**Comment by dwimjpurnomo** [comment]
[newVersionError.zip](https://github.com/lautenberger/elmfire/files/12910491/newVersionError.zip)

**Comment by lautenberger** [comment]
@dwimjpurnomo Try cloning the latest repo, set the environment variable `ELMFIRE_VER=2023.1015` and re-run. Do you get past the error now?
