### ISSUE TITLE
Error in script of real-world fuel/terrain under constant/uniform wind

### ISSUE THREAD

**Issue by ehsankazem** [lautenberger/elmfire#38]
There is an error in the script that i change lat & long of fuel data the simulation process fail and doesn't work
![elmfire](https://github.com/lautenberger/elmfire/assets/83070826/b09464a8-a7d7-4a66-b98b-a425f6b3e870)
![elmfire](https://github.com/lautenberger/elmfire/assets/83070826/e90353c6-1fdb-4ec8-b6c4-feb68ee96afe)

**Comment by lautenberger** [comment]
Hi, the coordinates (-130.281, 47.440) are in the Pacific Ocean so there's no fuel data there.

**Comment by ehsankazem** [comment]
Hello, thanks for your comment
but in other coords like lat=51.81363053328923 long=-123.18997280486167 
i get same error

**Comment by ehsankazem** [comment]
> Hello, thanks for your comment but in other coords like lat=51.81363053328923 long=-123.18997280486167 i get same error

@lautenberger

**Comment by lautenberger** [comment]
Those coordinates are in Canada, the fuel data are from LANDFIRE which is only US. I'm not familiar with fuel data in Canada, but if there's a dataset analogous to LANDFIRE I'll gladly add it in

**Comment by ehsankazem** [comment]
> Those coordinates are in Canada, the fuel data are from LANDFIRE which is only US. I'm not familiar with fuel data in Canada, but if there's a dataset analogous to LANDFIRE I'll gladly add it in

Ok, thank you for your guides

**Comment by lautenberger** [comment]
Sure, think - closing this issue for now but please do let me know if you encounter any additional problems!
