### ISSUE TITLE
Install elmfire without sudo access

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#48]
Hi Chris,
We are trying to use campus cluster to run elmfire. When installing elmfire it requires mpifort, which I believe is parallel computing for fortran. Unfortunately, the campus cluster does not have mpifort installed.
To install mpifort the command that I found is "sudo apt install mpich". But obviously we do not have sudo access for campus cluster.

What is the best way to solve it?

**Comment by lautenberger** [comment]
`mpifort` is a wrapper around the underlying fortran compiler for compiling against MPI libraries.  I'd be surprised if HPC resources at Cal don't have an MPI implementation installed - OpenMPI or MPICH in particular. You may have to do something like `module load mpi_implementation_compiler_version` . Try checking with the system administrator there to see if they can provide some guidance. 

If that's a dead end, you can always build OpenMPI from source in your user directory (`/home/dwi` or whatever) - it's not as hard as it sounds but definitely more work then `module load...`

**Comment by dwimjpurnomo** [comment]
They have mpiifort, with two "ii". It was installed but with many warnings. I'll try to run the tutorial, but now their system is down, and cannot do transfer data.

**Comment by lautenberger** [comment]
`mpiifort` should be the compiler wrapper for the Intel compiler...
