### ISSUE TITLE
Feature request: add runtime column to burned-acres-timings.csv

### ISSUE THREAD

**Issue by vvvvalvalval** [lautenberger/elmfire#49]
Use case: in a PiRPLO-ish context, estimate variations in total runtime as we consider various distributions of fire durations, without having to rerun simulation.

This would just add a column `runtime` to `burned-acres-timings.csv`, with the same semantics and units as the one in `fire_size_stats.csv`.

**Comment by lautenberger** [comment]
Closing this issue.
