### ISSUE TITLE
Add threshold tests to smoke output

### ISSUE THREAD

**Issue by fitnr** [lautenberger/elmfire#5]
Please add a config option to set a minimum fire size and mass release thresholds before writing smoke outputs. Fires that are under these thresholds need not be written out in smoke CSVs.
FYI @HoHsieh @mike-amodeo

**Comment by lautenberger** [comment]
Per our discussion last week, it seems that this test can be made exclusively on the basis of mass release and that we don't need to test for fire size. In the `smoke-metadata` branch I added the keyword `PM2P5_RELEASE_MIN_FOR_OUTPUT` to the `&SMOKE` namelist group. This is the threshold PM2.5 release - in micrograms - below which smoke files won't be dumped.

**Comment by lautenberger** [comment]
This is complete as of commit cfa2028dc5362c153c1256bab847d071664c458e.
