### ISSUE TITLE
Cannot run elmfire in cluster savio: gdalwarp problem

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#53]
After installation I try to run elmfire but there was an error with gdalwarp. The full log is attached
[nohup2.txt](https://github.com/lautenberger/elmfire/files/14043612/nohup2.txt)

**Comment by lautenberger** [comment]
Hi Dwi,

Is this the cluster you're running on?

https://docs-research-it.berkeley.edu/services/high-performance-computing/overview/

If so, it looks like the OS is Scientific Linux 7 which I'm not familiar with. Regardless, the key line in the output is:

```
gdalwarp: error while loading shared libraries: libproj.so.25: cannot open shared object file: No such file or directory
```
Basically, `gdalwarp` can't find the shared library libproj which *SHOULD* have been installed when gdal was built/installed. This is a common error when executing binaries that were built from source as opposed to being installed with the system package manager which I suspect is the case here. 

Do you get the same error message if you do `gdalwarp --version` from the shell? If so, try to find out if / where libproj is installed and add the appropriate directory to your `LD_LIBRARY_PATH`. 

Let me know if you get stuck, I can probably help but this is linux shared libraries not elmfire so it may be more expedient to reach out the the Savio system administrator.

**Comment by dwimjpurnomo** [comment]
Hi Chris,

Yes, its
https://docs-research-it.berkeley.edu/services/high-performance-computing/overview/

When I tried gdalwarp --version it showed something (GDAL 3.6.4)

The error is now 
ERROR 1: PROJ: proj_create_from_database: Open of /global/software/sl-7.x86_64/modules/langs/python/3.10/share/proj failed
I tried to cd to that directory and it worked fine.

I'll also try to contact the cluster help desk. But maybe you know how to solve this.

**Comment by lautenberger** [comment]
@dwimjpurnomo were you able to get this working? Although it's an issue on the Savio cluster and not an ELMFIRE issue I should be able to help you get it resolved. However, it's probably easier to work through this in an online meeting than here. Let's see if we can get it figured out in our regular meeting on Tuesday. If not, let's schedule some time later this week for a quick Zoom meeting. Talk soon

**Comment by dwimjpurnomo** [comment]
They have not responded.
That would be great. Thank you
