### ISSUE TITLE
Running elmfire on mulitple nodes

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#57]
Hi Chris

When I run ELMFIRE on savio using multiple nodes (each nodes has 20 cores), weird thing happened. Suddenly it created many .bin files but not the .bil and .hdr files. The created bin files start from a number until the last ensemble. Then the elmfire only run until the starting number - 1. The simulation somehow stopped and considered as complete with a message from "orted" in the job ID.

To illustrate:
Lets say we use 100 ensembles.
In one second .bin from 26 to 100 are already created but not the corresponding .bil and .hdr. Then elmfire continue running andreate the remaining ensemble (1 - 25). After the 25 ensembles are done, the simulation stop and considered as complete, without giving the .bil and .hdr outputs for ensemble 26 - 100. At the end of simulation the outputs created:
.bin (1 - 100)
.hdr (1 - 25)
.bil (1 -25)

This doesn't happen when using 1 node in SAVIO.

**Comment by lautenberger** [comment]
Thanks Dwi, if you attach your input deck I'll run locally to see if I can reproduce the error.

**Comment by dwimjpurnomo** [comment]
Hi Chris,

The input decks are here
https://drive.google.com/drive/folders/1rytDfsPmxqwUDsfNeiydxyta_V4R4ysX?usp=sharing

**Comment by dwimjpurnomo** [comment]
Hi Chris,

This is the input decks for the new version of ELMFIRE.
[inputSavio.zip](https://github.com/lautenberger/elmfire/files/14775358/inputSavio.zip)

**Comment by dwimjpurnomo** [comment]
I tested that in savio, it works with 1 node but not working with multinodes

**Comment by lautenberger** [comment]
Thanks, Dwi. I'm not sure why you're encountering the behavior that you're seeing, could it be caused by running from a directory that's not shared across nodes? But since 99.9% of the time (at least for me!) ELMFIRE is run on a single node, I'm going to leave this issue open so that I can eventually get to it, but put it on hold for now.

**Comment by lautenberger** [comment]
Hi @dwimjpurnomo, I finally found some time to look into this - thanks for your patience. 

With the most recent code, inter-node runs are working on my end including generation of all outputs, so try re-running after building from the latest repository. If you haven't done this already, also be sure to set `MULTIPLE_HOSTS = .TRUE.` in the `&SIMULATOR` namelist group. 

One more thing:  when calling mpirun (Open MPI 4.1.2)  I had pass it the flag `--mca btl_tcp_if_exclude 172.17.0.0/24,127.0.0.0/24` to get it to work, but that may be unique to my local environment.

**Comment by dwimjpurnomo** [comment]
Thank you, Chris. I will try this.

Best,

Dwi


Regards
Dwi Marhaendro J Purnomo

**Comment by dwimjpurnomo** [comment]
Its working now. Thank you!!!
